# Generated by Django 4.1.5 on 2023-01-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muallif',
            name='yosh',
            field=models.PositiveSmallIntegerField(default=45, null=True),
        ),
    ]
