# Generated by Django 3.2.16 on 2023-01-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0002_alter_muallif_yosh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='ish_vaqti',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
