# Generated by Django 3.2.16 on 2023-02-19 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asosiy', '0005_remove_record_foydalanuvchi'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='user_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
